### ISSUE TITLE
How To Set Key Name as a Variable in Javascript

### ISSUE THREAD

**Issue by jasonwiesner** [CapsCode-Website/blogfiles#1]
Hey Rahul,

Just wanted to share that in your "How To Set Key Name as a Variable in Javascript" article you have a minor typo in someValue as below:

obj = { ...obj, [key]: somaValue };

Thanks for the great content!

-Jason Wiesner

**Comment by capscode** [comment]
Hey Jason Wiesner,

Thank you for pointing this out.
I have corrected this and deployed.

thanks once again.
& glad that you liked this article.

~Rahul nag
